my_diss_django_project/urls.py
from registration.backends.simple.views import RegistrationView
from django.urls import reverse
from cupcake_site import views 
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


"""override redux package existing registration_register (when users Sign Up) to redirect to a custom user profile registration form"""
class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
      return reverse( 'cupcake_site:register_profile')

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('cupcake_site/', include('cupcake_site.urls')),
    path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
    path('accounts/register/', MyRegistrationView.as_view(), name='registration_register'),#override existing redux package URL mapping
    path('accounts/', include('registration.backends.simple.urls')),#out of the box django-registration-redux package for user authentication and login etc
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)# path for Media files 

posts/urls.py
from django.urls import path
from posts.views import PostCreate, PostDetail
from posts import views



app_name = 'posts'

urlpatterns = [
 
  path('', views.posts_index, name='posts_index'),  
  path('posts_create/', views.PostCreate.as_view(),name = 'posts_create'), 
  path('posts_detail/<int:pk>', views.PostDetail.as_view(), name='posts_detail'), 
]

posts/models.py
from django.db import models
from datetime import datetime
from django.urls import reverse
from django.contrib.auth.models import User #PostAuthor, CommentAuthor
from cupcake_site.models import UserProfile
from django.template.defaultfilters import slugify

"""Azzopardi & Maxwell "Tango with Django" (2019) & Traversy Media (2017) tutorial helped with these post models"""
#Meta inner class helps get rid of the extra default 's' on Postss, as displayed on /admin page 
"""Status and Display choices adapted from The Abhijeet https://github.com/TheAbhijeet/Django_blog/blob/master/blog/models.py"""
#post has one author but authors have many posts, relationship is ForeignKey to userprofile
#For the slug Adding unique=True attrubute after database is created avoids database conflicts, as posts are only for registered users. 

STATUS = (
        (0, "Draft"),
        (1, "Publish")
)

      
class Posts(models.Model):
    title = models.CharField(max_length=200, blank=True)# choices=DISPLAY, default=1)
    slug = models.SlugField(max_length=200, blank=True)#add unique=true attribute after database is created.
    body = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    created_at = models.DateTimeField(default=datetime.now, blank=True)
    last_modified = models.DateTimeField(auto_now=True)
    status= models.BooleanField(default=True)# so posts can be in published or draft status
    post_image = models.ImageField(upload_to ='post_images/', blank=True)

    class Meta:
        verbose_name_plural = "Posts"
        ordering=['-created_at']
        

    def __str__(self):
        return self.title

    #To display the post title with a clean slug instead of default post id 
    def save(self, *args, **kwargs,):
        self.slug = slugify(self.title)
        super(Posts, self).save(*args, **kwargs)

    #To display a default picture when a user does not load one
    def picture_or_default(self, default_path="/static/images/digitalcakes.jpg"):
        if self.picture:
            return self.picture
        return default_path
      



        

posts/forms.py
from django import forms
from string import Template
from django.utils.safestring import mark_safe
from django.forms import ImageField
from my_diss_django_project import settings
from cupcake_site.models import User
from posts.models import Posts
from crispy_forms.helper import FormHelper
from django.core.files.images import get_image_dimensions

class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Posts
        exclude = ('slug', 'user')

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
       
    def clean_title(self):
        title = self.cleaned_data['title']
        if Posts.objects.filter(user=self.user, title=title).exists():
            raise forms.ValidationError("You have already written a post with the same title.")
        return title

     

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.http import HttpRequest
from django.urls import reverse
from django.urls import reverse_lazy

from datetime import datetime

from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from posts.forms import PostCreateForm
from django.views import View
from django.views.generic.detail import DetailView
from posts.models import Posts
from django.views.generic.edit import CreateView


"""any user can view a list of titles of published blog posts code adapted from Traversy Media (2017) tutorial "Django crash course" """
def posts_index(request):
    try:
        posts=Posts.objects.all()[:10] #gets the first 10 posts to display
    except Posts.DoesNotExist:
        return None 
    context = {
            'posts': posts
            }
    return render(request, 'posts/posts_index.html', context)

"""allow a registered user to create a new post, adapted from tutorial https://www.agiliq.com/blog/2019/01/django-createview/#using-createview"""

class PostCreate(CreateView):
    template_name = 'posts/posts_create.html'
    form_class = PostCreateForm
    """lazy reverse returns an object, on success of form creation redirect user to the post_index.html page""" 
    success_url = reverse_lazy('posts:posts_index')


    """ Check the user is authenticated, to get the post.user, request the user before the form is saved"""
    @method_decorator(login_required, name='form_valid') 
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        """redirect to the post_index.html page"""
        return HttpResponseRedirect(self.get_success_url()) 

        
    """populate the form body with initial data"""
    def get_initial(self, *args, **kwargs):
        initial = super(PostCreate, self).get_initial(**kwargs)
        initial['body'] = 'My blog post'
        return initial    

    """build keyword arguments to instanticate the form https://docs.djangoproject.com/en/2.2/ref/class-based-views/mixins-editing/"""
    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super(PostCreate, self).get_form_kwargs(*args, **kwargs)
        kwargs['user'] = self.request.user
        return kwargs

"""class to display the view of a single post instance using generic DetailView created adapted from https://www.agiliq.com/blog/2019/01/django-when-and-how-use-detailview/"""
"""no login decorator is required as any user can view post details"""
class PostDetail(DetailView):
    model = Posts
    template_name = 'posts/posts_detail.html'

    def get(self, request, *args, **kwargs):
        post = get_object_or_404(Posts, pk=kwargs['pk'])
        context = {'post': post}
        return render(request, 'posts/posts_detail.html', context)

templates/posts/posts_create.html
{%extends 'cupcake_site/base.html' %}
{% load staticfiles %}
<!--Create and display PostCreatView Form to add a new post if user is logged in. -->
{% block title_block %}
AddPost 
{% endblock %}


<head> 
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
<!--container, row, col_x and justify-content-centre creates a simple layout with one row and one column-->
</head>  

{% block body_block %}

{% load crispy_forms_tags %}
 <div class="jumbotron p-4">
    <div class="container">
     <!-- ony authenticated users should access this page -->
       <h1 class="jumotron-heading">{{post.user}} create your new Blog article</h1>



<!--Crispy form-->
 {% block main %} 
     <!--display post details form enable them to update values title, picture, body, status-->
        <form method = "post" action="." enctype="multipart/form-data">
              {% csrf_token %} 
              {{ form|crispy}}
              <input type="submit" name="posts_create" value="Submit">
        </form>
        </div>
        </div>
        </div>                 
  {% endblock %}              

{% endblock %}

templates/posts/posts_detail.html
{% extends 'posts/posts_layout.html' %}
{% load staticfiles %}

{% block blog_content %}

<h3 class = "centre-align blue lighten-4", class="container centre-align">{{post.title}} by {{post.user}}</h3>
      <div class="container">
      {% if post.post_image %}
       <br/>
        <img src="{{ MEDIA_URL }}{{ post.post_image }}" width="300" hight="300" alt="{{post.title}}'s blog image {{post.post_image.name}}" />   
        <br/>
      {% else %}
      <!--if media files are not loading, render a default static file-->
      <br/>
      <img src="{% static 'images/digitalcakes.jpg' %}" width="300" height="300" />
      <br/>
      {% endif %}
       <div class = "card-content">
            {{post.body}}
            <br/>
        </div>
        <div class = "card-action">
            {{post.created_at}} 
            <br/>
        <br/>
        <a href="{% url 'posts:posts_index' %}"  class="btn btn-secondary" role="button">Back to Blogs</a>
        </div>
    </div>   

{% endblock %}

templates/posts/posts_index.html
{% extends 'posts/posts_layout.html' %}
{% load staticfiles %}

{% block blog_content %}
 
    <h4 class = "container center-align"><n></n><n></n>l a t e s t &nbsp;&nbsp;p o s t s</h4>
    <h6 class = "centre-align blue lighten-4", class="container centre-align"><h6>Sign up to post your coding learning journey here. <br/> You could outline your progress on a project, or share experiences at a tech event, career pathway or anything you would like to contribute.</h6>

    <ul class = "collection">
        {% for post in posts %} 
            <li class = "collection-item"><a href="{% url 'posts:posts_detail' post.pk %}" >{{post.title}}</a></li>
        {% endfor %}
    </ul>
    {% if user.is_authenticated %} 
    <div>
    <a href="{% url 'posts:posts_create' %}"  class="btn btn-secondary" role="button">Add New Blog Post</a> 
    </div>
    {% endif %} 

{% endblock %}

templates/posts/posts_layout.html
{% extends 'cupcake_site/base.html' %}
<!-- @author Cass 2140148s July 2019  -->
   
<!--Browser tab title-->	
{% block title_block %}
    BlogCupcakeCode
{% endblock %}
		
 <div class = "container"> 
{% block body_block %} 

<!-- Blog container for posts MaterizeCSS getting started link is copied from the CND box. -->

<!--Different Design style in a box <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"> -->

    <header class = "container center-align">
        <h1><b>B L O G  - learning journey</b></h1> 
    </header>
    
    <!--so each template is different wrap into a container, this is Jinja below in brackets-->
    <div class = "container">
        {% block blog_content %}
        {% endblock %}
    </div>
        
       
{% endblock %} 
<!--any footer is inherited from cupcake_site base template-->
  