cupcake_site/urls.py
from django.urls import path
from cupcake_site import views
#from cupcake_site.views import AboutView #always import seperately 
#from cupcake_site.views import IndexView  

"""@author Cassie Spalding 2140148s dissertation project 2019 
this file handles urls that startwith cupcakesite/ """

"""note regarding django registration redux, url patterns - see login.html and other templates in templates/registration dir"""

app_name = 'cupcake_site'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'), 
    path('about/', views.AboutView.as_view(), name='about'),
    path('career/', views.career, name='career'),
    path('tools/', views.tools, name='tools'),
    path('tools/<slug:category_name_slug>/', views.show_category, name='show_category'),
    path('add_category/',views.CategoryCreateView.as_view(), name='add_category'),
    path('tools/<slug:category_name_slug>/add_page/', views.add_page, name='add_page'),
    path('register_profile/', views.RegisterProfileCreateView.as_view(), name='register_profile'),
    path('profile/<username>/', views.ProfileCreateView.as_view(), name='profile'),
    path('profiles/', views.ListProfilesView.as_view(), name='list_profiles'),
    path('cupcake_tutorial/', views.TutorialView.as_view(), name='cupcake_tutorial'),
    path('search/', views.SearchView.as_view(), name='search'),
    
]  

my_diss_django_project/urls.py
from registration.backends.simple.views import RegistrationView
from django.urls import reverse
from cupcake_site import views 
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


"""override redux package existing registration_register (when users Sign Up) to redirect to a custom user profile registration form"""
class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
      return reverse( 'cupcake_site:register_profile')

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('cupcake_site/', include('cupcake_site.urls')),
    path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
    path('accounts/register/', MyRegistrationView.as_view(), name='registration_register'),#override existing redux package URL mapping
    path('accounts/', include('registration.backends.simple.urls')),#out of the box django-registration-redux package for user authentication and login etc
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)# path for Media files 

posts/urls.py
from django.urls import path
from posts.views import PostCreate, PostDetail
from posts import views



app_name = 'posts'

urlpatterns = [
 
  path('', views.posts_index, name='posts_index'),  
  path('posts_create/', views.PostCreate.as_view(),name = 'posts_create'), 
  path('posts_detail/<int:pk>', views.PostDetail.as_view(), name='posts_detail'), 
]

cupcake_site/forms.py
from django import forms
from my_diss_django_project import settings
from cupcake_site.models import Page
from cupcake_site.models import Category
from cupcake_site.models import User
from cupcake_site.models import UserProfile
from crispy_forms.helper import FormHelper
from django.core.files.images import get_image_dimensions

"""Learning Tools category form"""
class CategoryForm(forms.ModelForm):
  name = forms.CharField(max_length=128, help_text="Please enter the category name.")
  views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
  likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
  slug = forms.CharField(widget=forms.HiddenInput(), required=False)
  
  
  """Specify model for form, and visible fields to be displayed""" 
  class Meta:
    model = Category
    fields = ('name',)

"""Learning Tools Page link form"""
class PageForm(forms.ModelForm):
  title = forms.CharField(max_length=128, help_text="Please enter the title of the web page.")
  description = forms.CharField(max_length=500, help_text="Describes why this page is a great resource to help direct others towards useful information.")
  url = forms.URLField(max_length=200, help_text="Please enter the web address of the page you want to add, starts with http:// Hint: you can copy and paste the link from your browser.")
  views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

  class Meta:
    model = Page
    exclude = ('category',)

  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)

  """override the form to handle missing data/ default fields for the url""" 
  def clean(self):
    cleaned_data = self.cleaned_data
    url = cleaned_data.get('url') 
    #Note: the get function will return None if user enters nothing as new form will not exist

    """HANDLING SECURE https:// too!
    if the url is not empty and doesn't start with 'http://' then automatically input 'http://'  """
    if url and not (url.startswith('http://') or url.startswith('https://')):
      url = 'http://'+ url
      cleaned_data['url'] = url
      #always end clean() by returning a reference to the cleaned_data dictionary
      return cleaned_data

"""Create A User Profile"""
class UserProfileForm(forms.ModelForm):#when a userprofile is made it wont yet have instance of a user unless already registered
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self.helper = FormHelper()   

  class Meta:
    model = UserProfile
    fields = ('bio', 'picture')
    clean_pic=('picture')
   
    """Code adapted from https://stackoverflow.com/questions/6396442/add-image-avatar-field-to-users-in-django/6396744"""
    def clean_pic(self):
        pic = self.cleaned_data['picture']

        try:
            w, h = get_image_dimensions(pic)

            #validate dimensions
            max_width = max_height = 100
            if w > max_width or h > max_height:
                raise forms.ValidationError(
                    u'Please use an image that is '
                     '%s x %s pixels or smaller.' % (max_width, max_height))

            #validate content type
            main, sub = pic.content_type.split('/')
            if not (main == 'image' and sub in ['jpeg', 'pjpeg', 'gif', 'png']):
                raise forms.ValidationError(u'Please use a JPEG, '
                    'GIF or PNG image.')
            #validate file size
            if len(pic) > (20 * 1024):
              raise forms.ValidationError
            (u'Your Profile picture file size may not exceed 20k.')

        except AttributeError:
            pass
            """
            Handles case when updating the user profile
            and does not supply a new profile picture
            """

        return pic

cupcake_site/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponse
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from crispy_forms.helper import FormHelper
from django.views import View
from django.views.generic import CreateView
from django.utils import timezone
from datetime import datetime
from django.utils import timezone

from cupcake_site.models import Category, Page, UserProfile
from cupcake_site.forms import CategoryForm, PageForm, UserProfileForm

"""
Cassie Spalding 2140148s
Code for the view's adapted and guided by Azzopardi & Maxwell "Tango with Django" (2019)"""

"""index view is the Home page for the web application site"""
class IndexView(View):
  """construct a dictionary to pass to the template html as its context for data to be rendered."""
  def get(self, request):
    return render(request, 'cupcake_site/index.html')

"""Tutorial view is the page for users try a cupcake tutorial"""
class TutorialView(View):
  """currently under construction"""
  def get(self, request):
    return render(request, 'cupcake_site/cupcake_tutorial.html')

"""About page"""
class AboutView(View):
  def get(self, request):
    context_dict={}
    return render(request, 'cupcake_site/about.html', context=context_dict)

"""Career carsousel"""
def career(request):
  context_dict={'boldmessage': 'We need more women in tech'}
  return render(request, 'cupcake_site/career.html', context=context_dict)

"""Search view to implement search feature"""
class SearchView(View):
  """currently under construction"""
  def get(self, request):
    return render(request, 'cupcake_site/search.html')

"""Learning Tools Categories Page"""
def tools(request):
  """display all the categories in a list, to only show a  maximum 10  use [:10]"""
  category_list = Category.objects.all()
  page_list = Page.objects.order_by('views')[:5]

  context_dict ={}
  context_dict ['categories'] = category_list
  context_dict ['pages'] = page_list
  visitor_cookie_handler(request)
  context_dict['visits'] = request.session['visits']
  return render(request, 'cupcake_site/tools.html', context=context_dict)

"""Display a list of links for the selected Learning Tool"""
#TODO write def create_context_dic for this class"""
def show_category(request, category_name_slug):
  context_dict={}
  try:
    # get method returns DoesNotExist or instance // try/catch  handles exception if no categories exist
    category= Category.objects.get(slug=category_name_slug)
    # filter method  return a list of page objects or an empty list
    pages= Page.objects.filter(category=category)
    # Save results from filter
    context_dict['pages'] = pages
    # add the category object from database to the context dictionary, which is used to verify it exists in the template
    context_dict['category']= category
  except Category.DoesNotExist:
    # set context_dict to None as none found, DoesNotExist exception is displayed
    context_dict['pages'] = None
    context_dict['category']= None
  return render(request, 'cupcake_site/tools_category.html', context=context_dict)

"""Add a page link to a specified Learning Tool category"""
# the slug eliminates white spaces in URL, is the title of the category passed in
def add_page(request, category_name_slug):
  try:
    category = Category.objects.get(slug=category_name_slug)
  except Category.DoesNotExist:
    category = None

  form = PageForm()
  if request.method =='POST':
    form = PageForm(request.POST)

    if form.is_valid():
      if category:
        page = form.save(commit=False)
        page.category = category
        page.view =0
        page.save()
    #once page form is created, check it has a valid category
    #category_name_slug passed in parameter, by providing a value in dictionary as kwargs to the reverse function, Django can formulate the url
        return redirect(reverse('cupcake_site:show_category', kwargs={'category_name_slug':category_name_slug}))
    else:
      print(form.errors)

  context_dict = { 'form':form, 'category':category }
  return render(request, 'cupcake_site/add_page.html', context=context_dict)

"""Form to Add a new Category to Learning Tools and process"""
class CategoryCreateView(CreateView):
    @method_decorator(login_required)
    def get(self, request):
      form=CategoryForm()
      return render(request, 'cupcake_site/add_category.html', {'form': form})

    @method_decorator(login_required)
    def post(self, request):
      form= CategoryForm(request.POST)

      if form.is_valid():
        form.save(commit=True)
        return tools(request)
      else:
        print(form.errors)
      return render(request, 'cupcake_site/add_category.html', {'form': form})

"""Create a User Profile, assumes a user has signed up and created a django.contrib.auth.models.User instance prior"""
class RegisterProfileCreateView(CreateView):
    @method_decorator(login_required)
    def get(self, request):
      form=UserProfileForm()
      return render(request, 'cupcake_site/profile_registration.html', {'form': form})

    @method_decorator(login_required)
    def post(self, request):
      form=UserProfileForm(request.POST, request.FILES)

      if form.is_valid():
        user_profile = form.save(commit=False)#creates user profile instance, but does not save it
        #allows user to upload data and maps profile to user registered
        user_profile.user = request.user
        user_profile.save()# saves the new data attributes to the userprofile
        form.helper.include_media = True
        #redirect index page
        return redirect ('cupcake_site:index')

      else:
        print(form.errors)

      return render(request, 'cupcake_site/profile_registration.html', {'form': form})

"""Display a registered users profile, allow a registered user to view and amend their profile"""
class ProfileCreateView(CreateView):
    def get_user_details(self, username):
      try:
          user = User.objects.get(username=username)
      except User.DoesNotExist:
          return None

      userprofile = UserProfile.objects.get_or_create(user=user)[0]
      include_media = True
      form = UserProfileForm({'bio': userprofile.bio,
                              'email':userprofile.email,
                              'picture': userprofile.picture})
      return (user, userprofile, form)


    @method_decorator(login_required)
    def get(self, request, username):
        try:
            (user, userprofile, form) = self.get_user_details(username)
        except TypeError:
            return redirect('cupcake_site:index')

        context_dict = {'userprofile': userprofile,
                        'selecteduser': user,
                        'form': form,
                        }
        form.helper.include_media = True
        return render(request, 'cupcake_site/profile.html', context_dict)

    @method_decorator(login_required)
    def post(self, request, username):
        try:
            (user, userprofile, form) = self.get_user_details(username)
        except TypeError:
            return redirect('cupcake_site:index')

        #To test if user is authenticated this is a second check, method decorator already checks this.
        if user == request.user:
            form = UserProfileForm(request.POST, request.FILES, instance=userprofile)

            if form.is_valid():
              form.save(commit=True)
              form.helper.include_media = True
              return redirect('cupcake_site:profile', user.username)

            else:
                print(form.errors)

            context_dict = {'userprofile': userprofile,
                            'selecteduser': user,
                            'form': form}
        form.helper.include_media = True
        return render(request, 'cupcake_site/profile.html', context_dict)

"""Allow a user to see a list of Members"""
class ListProfilesView(View):
    @method_decorator(login_required)
    def get(self, request):
      profiles = UserProfile.objects.all()

      return render(request, 'cupcake_site/list_profiles.html',{'userprofile_list':profiles})

"""Cookies and Visits  """
def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)

    if not val:
        val = default_val

    return val

def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))

    last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')

    if (datetime.now() - last_visit_time).days > 0:
        visits = visits + 1
        request.session['last_visit'] = str(datetime.now())
    else:
        request.session['last_visit'] = last_visit_cookie

    request.session['visits'] = visits

templates/cupcake_site/about.html
{% extends 'cupcake_site/base.html' %}
{% load staticfiles %}

{% block title_block %}   
    CupcakeAbout
{% endblock %}

   
{% block body_block %}
 <header class = "container centre-align">
 <!-- divide page into two areas left for main text and right as a sidebar area -->
 <!--Left side column for main area text-->
<div class="row">
<div class="col-sm-8">
<div class="container">
   <h1>About CupCakeCode..</h1><br /> 
<div >
<img src="{% static 'images/women.coffee.laptop.jpg' %}"  alt="Picture of person with coffee and laptop" />
</div> 
<p>Good at organising? Juggling the household, family commitments, clubs and events, everyone's likes dislikes, everyone's social calendar, laundry required for each day of the week, paying bills, correspondence, work, and being adaptable to fit around others. Applying your life skills and learning to code could make you more employable in the future. The great thing about coding is nobody knows it all, and there's always something new to learn. I've found coding surprisingly creative and you could too! </p>
<div >
<img src="{% static 'images/model-morph.jpg' %}" width="600" height="330"    alt="Picture of icing model desk with figure" />
</div> 
<p>It would be great if I could inspire you into trying out some code or even enrolling on a course. I've found it much more interesting and creative than I could ever have imagined. </p>
<p>Embracing technology can empower your confidence in any job and open the door to some great career opportunities.  Join the Digial Revolution and start learning, check out Learning tools to find out how to get started, find free resources, meetup groups and much more. Ultimately if we want to have a voice, and help to shape our evolving tech culture, rather that shying away, it's essential we embrace technology.</p>
<!--close container --> 
</div>
<!--close column-->
</div>

<!--Right side column for smaller side bar area-->
<div class="col-sm-4">

   <h1>Top Tips...</h1><br />  
      <!--Image-->
      <img src="{% static 'images/dark-computer-cake.jpg' %}"  width="300" height="330"      alt="Picture of Computer Cake" />
      <!-- New line -->
      <br /> 
      <p>Links to Facts </p>
      <!-- List links here -->
      <br/>

   <h1>Did You Know...</h1><br /> 
      <!--Image-->
      <img src="{% static 'images/women-working.jpg' %}" width="300" height="200"    alt="Picture of person at work in IT " />
      <!-- New line -->   
      <br />
      <p>Links to Facts </p>
      <!-- List links here -->
      <br/>

   <h1>Women in Tech</h1><br />
      <!--Image--> 
      <img src="{% static 'images/photo-women-in-tech.jpg' %}" width="300" height="200"       alt="Picture of group of women working in IT" />
      <!-- New line -->   
      <br />
      <!--List Links here. Currently Career's link takes users to view a carousel --> 
      <p>Links to <a href="{% url 'cupcake_site:career' %}">Careers</a></p>
      <br/>
   <!--close column-->
    </div>
   <!--close rows-->
    </div>
{% endblock %} 

templates/cupcake_site/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>
<!--  #author Cassie Spalding 2140148s dissertation project 2019 this is the BASE layout for the site.
Note bootstrapCND source is the from  "getting started" https://getbootstrap.com/docs/4.0/getting-started/introduction/
Note there is also a JavaScript & Poppie from the same source -->

<!--Browser tab title-->
<title>
{% block title_block %}
{% endblock %}
</title>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="X-UA-Compatible" content="ie=edge">

<!-- CSS bootstrap 4 -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

<!-- Popper JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

</head>

<body>
<!--Navigation Bar and Header for the site-->
    <header class = "container centre-align">
<!--divide page into two areas-->
<div class="row">
<!--left of page holds website cupcake code title over cupcake image container-->
  <div class="col-sm-3">
    <div class="container">
    <!--TEXT OVER IMAGE CARD-->
    <div class="card card-blog">
      <div class="card">
        <img id="image" src="{% static 'images/rainbow_cupcakes.jpg' %}" alt="Cupcake Code Background image logo" style="width:100%;"></a>
      </div>
       <div class="card-body text-center carousel-caption">
        <h4 class="card-title">CUPCAKE CODE<></h4>
          <div class="card-description">
            <div class="table-responsive">
            </div>
        </div>
      <!--close card, then close card-blog-->
      </div>
    </div>
    <!--close container, then close column-->
    </div>
  </div>

  <div class="col-sm-9">
   <!--right of page is wider area for the navigation bar -->
    <div class="container">
  <!--logo header above navigation bar with Login/Logout and Admin Buttons-->
    <h2>&nbsp;&nbsp;&nbsp;CUPCAKE CODE <> anyone can code....
     <!--additional buttons features for authenticated users, only display if authenticated go here-->
     {% if user.is_authenticated %}
      <a href="{% url 'auth_logout' %}" class="btn btn-secondary" role="button">Logout</a>
     {%else%}
      <a href="{% url 'auth_login' %}" class="btn btn-secondary" role="button">Login</a>
    {% endif %}
    {% if user.is_staff %}
      <a href="{% url 'admin:login' %}"  class="btn btn-secondary" role="button">Admin</a>
    {% endif %}
    </h2>
    <!--Navigation BAR adapted from https://getbootstrap.com/docs/4.0/components/navbar/#responsive-behaviors-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <!--HOOK - a space for a heading in Nav Bar if requried later, not required now - the example is commented out-->
    {% comment %} <a class="navbar-brand" href="#">CupCakeCode</a> {% endcomment %}

    <!--List of Links for Navigation Bar-->
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'cupcake_site:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cupcake_site:about' %}">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'posts:posts_index' %}">Blog</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cupcake_site:tools' %}">Learning Tools</a>
      </li>
       <!--extra features for logged in users -->
       {% if user.is_authenticated %}
        <li class="nav-item">
        <a class="nav-link" href="{% url 'cupcake_site:profile' user.username %}">My Profile</a>
      </li>
       <li class="nav-item">
        <a class="nav-link" href="{% url 'cupcake_site:list_profiles' %}">Members</a>
      </li>
      {% else %}
      <!--Sign up button if not logged in -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'registration_register' %}">SignUp</a>
      </li>
       {% endif %}
    </ul>
    <!--Search Bar-->
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <!--When the button is pressed the view.search redirects to the template search.html-->
      <a href="{% url 'cupcake_site:search' %}" class="btn btn-outline-success" role="button">Search</a>
      <!--<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
    </form>
  </div>
</nav>
</div>

    <div class="container">
     <div class="col-sm-4">
   <!--HOOK extra space for additional image or info if necessary for future-->

    </div>
<!--close the above nav bar column, then close the container-->
</div>
</div>
<!--close the row-->
</div>
</header>
 <!--Templates extending this base place content inside body block-->
<div>
{% block body_block %}
{% endblock %}
</div>
<!--This is the footer hook for contact info as a grey button TODO map url and write view and template -->
<br/>
{% comment %} <div class = "container">
      <a href="{% url 'cupcake_site:contact' %}"  class="btn btn-secondary" role="button">Contact Us</a>
</div> {% endcomment %}
</div>
</body>
</html>

templates/cupcake_site/cupcake_tutorial.html
{%extends 'cupcake_site/base.html' %}
{% load staticfiles %}

{% block title_block %}
Cupcake Code Trial
{% endblock %}

{% block body_block %}
<header class = "container center-align">
    <h1><b> Cupcake Code Tutorials </b> </h1><br/>
    <h6>Page under construction. This service is currently unavailable.</h6>
</header>
{% endblock%}

templates/cupcake_site/index.html
{% extends 'cupcake_site/base.html' %}
{% load staticfiles %}

{% block title_block %}   
    HomeCupcakeCode
{% endblock %}

{% block body_block %}
<!--Page is split into equal columns-->
<header class = "container centre-align">
<div class="row">

<!-- Page Left Row-->
<div class="col-sm-6">
<div class="container">
<!--Welcome message or, if logged in Hello username-->
{% if user.is_authenticated %}
    <h5>Hello  {{ user.username }}</h5> 
{% else %}
    <h5> Welcome!</h5><h6><a href="{% url 'registration_register' %}" >Sign up</a> to experience more awesome features of this site!</h6>
{% endif %}
<p>Welcome to this information website aimed at encouraging women to learn to code. 
Why not try out some code now? Click the red Start button for a cup cake themed coding tutorial.</p>
<!--Card display Cupcake Tutorial red button on Computer desk image overlayed with text-->   
<div class="card card-blog">
    <div class="card">
    <!--Image-->
        <img id="image" src="{% static 'images/plantsLaptop.jpg' %}" alt="Picture of a Desk with PC and plants" style="width:100%;">
        </div>
    <!--Text overlayed on image-->
    <div class="card-body text-centre carousel-caption">
        <h3 class="card-title" >!! TRY SOME CODE !! </h3>
        <div class="card-description"><strong>3 min code fun on cupcakes</strong>
            <div class="table-responsive">go go go
            </div> 
        </div>
    <!--Start Button overlayed on image-->
    <div class="card-footer">
        {% comment %} todo map link url to app <a href="{% url 'cupcake_site:cupcake_tutorial' %}"{% endcomment %}
        <a href="{% url 'cupcake_site:cupcake_tutorial' %}" class="btn btn-danger btn-round">CLICK HERE TO START</a>
        </div> 
    <!--close card-->
    </div>
    <!--close blog card--> 
    </div>

<!--text beneath main image-->
<br>
<p>For more coding exercises and lessons see Learning Tools <a href="{% url 'cupcake_site:tools' %}" >Click Here</a>. Like cakes? I'm sure you've baked a few cupcakes over time, if you can follow instructions in a cookbook you may find learn to code fun. There is an amazing quantity of resources available on-line and free guidance on offer. Once you get started, like baking cakes, it's actually pretty addictive. </p>
<!--lower left page image-->
<div>
<img src="{% static 'images/vanilla1_cupcakes.jpg' %}" style="width:100%;" alt="Picture of cupcakes" />
</div>
<!--Close Grid Column-->
</div>
<!--Close Grid Container-->
</div>

<!-- Page  Right row -->
<div class="col-sm-6">
<div class="container">
<h5>I've set up this site to encourage you to start coding! </h5><p>There are so many reasons to get on board the digital revolution, understanding tech helps us protect and guide our children. Developing tech skills can lead to better career prospects.</p>
<img src="{% static 'images/Jo.jpg' %}" width="550" height="340"    " alt="Picture portrait of web author" />
<!--text under image of person-->
<br><br>
<p>I have been coding for 2 years, it all started with by wanting to know more about how to protect my kids on-line. <a href="{% url 'posts:posts_index' %}">Read More</a> Check out my Blog if you would like to find out how I got into coding, and why more of us should...as well as many more inspirational stories from women in tech. </p>
<br>
<div>
<img src="{% static 'images/digitalcakes.jpg' %}" width="550" height="340" alt="Picture of digital cup cakes" />
</div>
</div>
<!-- Close Card  --> 
</div> 
<!-- Close Grid column -->
</div>
<!-- Close Container -->
</div>
<!-- Close Row -->
</div>
    
{% endblock %}

templates/cupcake_site/tools_category.html
{% extends 'cupcake_site/base.html' %}

{% block title_block %}   
  {% if category %}
      {{ category.name}}CupcakeCode
  {% else %}
      Unknown category
  {% endif %}
{% endblock %}

{% block body_block %}
<div>
<header class = "container center-align">
<!--If the category exists, display the category name-->
  {% if category %}
    <h1><b> {{ category.name}} </b> </h1><h6>Clicking the link takes you to view the page, to return to this site Click the back arrow in your browser or Right Click the links to open in a new tab.</h6>
</header>
<!--Display the list of page links for this learning tool category-->
<div class = "container">
<h3 class = "centre-align blue lighten-4", class="container centre-align">LINKS</h3>
  <div class = "card-content">
    <div>
        {% if pages %}
        <ul>
        <!--Display the list of pages -->
          {% for page in pages %}
            <li><a href="{{ page.url }}">{{ page.title}}</a> <br/>{{page.description}} </li>
          {% endfor %}
        </ul> 
        {% else %}
        <!--Display message if no pages in the list -->
          <strong>No pages currently in category.</strong>
        {% endif %}
     </div> 
    </div>
<div class = "container">
  <br>
  <!--authorised users can add a page-->
    {% if user.is_authenticated %} 
      <h6>Found something useful, want to share with others? Why not add a new page to this category of learning tools.</h6>
      <!--Add Page Button-->
      <a href="{% url 'cupcake_site:add_page' category.slug %}"  class="btn btn-secondary" role="button">Add Page </a>
    {% endif %}
      <!--Go Back button-->     
       <a href="{% url 'cupcake_site:tools' %}"  class="btn btn-secondary" role="button">Back to Learning Tools</a>
    </div>

<!--If the category does not exit-->
{% else %}
  <p>The specified category does not exist!</p>
</div> 
{% endif %}
    </div>
  <!--Close Card--> 
  </div>
  <!--Close Container-->
</div> 
{% endblock %}